#!/bin/sh

ovs-appctl -t ovs-vswitchd exit
ovs-appctl -t ovsdb-server exit
rm /etc/openvswitch/vtep.db
rm /etc/openvswitch/conf.db
ovsdb-tool create /etc/openvswitch/vtep.db /usr/share/openvswitch/vtep.ovsschema
/etc/init.d/openvswitch-switch start
ovs-appctl -t ovsdb-server ovsdb-server/add-db /etc/openvswitch/vtep.db

